name: milliy_shifo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  file_picker: ^10.2.0
  flutter_sound: ^9.28.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Splash/
    - assets/succesfully/
    - assets/doctors/
    - assets/logos/