// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOeDblcrUoE01WCAuD89ru7bIGLiY0eqs',
    appId: '1:381188917720:android:2e7af09d9e696e17f20aad',
    messagingSenderId: '381188917720',
    projectId: 'milliyshifo-92a2f',
    storageBucket: 'milliyshifo-92a2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYgZiaKIdbmFnQ7KDUvSx7WOtqSApVZUQ',
    appId: '1:381188917720:ios:2434fcee6fdcb8c0f20aad',
    messagingSenderId: '381188917720',
    projectId: 'milliyshifo-92a2f',
    storageBucket: 'milliyshifo-92a2f.firebasestorage.app',
    androidClientId: '381188917720-k9r2ai0a28jn0l60edqut4f461fuqvct.apps.googleusercontent.com',
    iosClientId: '381188917720-0s3idujc57e95q1cuevs1nv2ps0qqspl.apps.googleusercontent.com',
    iosBundleId: 'com.example.milliyshifo',
  );

}